---
name: Home-NG Tunneling
version: 0.0.23
slug: home-ng_tunneling
description: Create tunnel
url: https://github.com/Dylan-Infogenius/tunnel-home-NG/tree/main/homeng_tunnel
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
webui: "http://dylan.home-ng.app:7123"
homeassistant_api: true
hassio_api: true
hassio_role: manager
stdin: true
init: false
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
options:
  api_key: "" 

schema:
  api_key: str