---
name: Home-NG Tunneling
version: 0.0.5
slug: home-ng_tunneling
description: Create tunnel
url: https://github.com/Dylan-Infogenius/tunnel-home-NG/tree/main/homeng_tunnel
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
homeassistant_api: true
hassio_api: true
hassio_role: manager
stdin: true
host_network: true
privileged: true

init: false
options:
  server_public_key: "demo-key"
  endpoint: "vpn01.home-ng.app"

schema:
  server_public_key: str
  endpoint: str
  client_ip: str
  server_ip: str
  log_level: list(debug|info|warning|error)?