---
name: Home-NG Tunneling
version: 0.0.19
slug: home-ng_tunneling
description: Create tunnel
url: https://github.com/Dylan-Infogenius/tunnel-home-NG/tree/main/homeng_tunnel
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
homeassistant_api: true
hassio_api: true
hassio_role: manager
stdin: true
init: false
ports:
  80/tcp: null
  51820/udp: 51820
ports_description:
  80/tcp: WireGuard peers status API
  51820/udp: "WireGuard: forward this port in your router"
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
options:
  api_key: "" 

schema:
  api_key: str